model:
  grid-id: 2534
  feeder: False
  feeder-id: 0
opt:
  solver: 'gurobi'
  opt_storage: False
  opt_ev: False
  opt_hp: True
  objective: 'minimize_loading'
  timesteps_per_iteration: 96
  iterations_per_era: 7
  overlap_iterations: 24
logger:
  log_file: 'log.txt'
  log_to_file: True
directories:
  load_integration:
    import: "elia_ding0_grids"
    export: "load_n_gen_grids"
  emob_integration:
    import: "load_n_gen_grids"
    export: "load_n_gen_n_emob_grids"
    flexbands: ""
  hp_integration:
    import: "load_n_gen_n_emob_grids"
    export: "load_n_gen_n_emob_n_hp_grids"
  feeder_extraction:
    import:
    export:
    settings:

