opt:
  run: "first_run"
  import_dir: "load_n_gen_n_emob_n_hp_grids_extracted"
  mvgds: [2534, 176, 177, 1056, 1690, 1811]
#  mvgds: [2534]
  feeder: False
  solver: 'gurobi'
  opt_bess: False
  opt_hp: True
  opt_emob: True
  emob_sectors: ["work", "home"]
  objective: 'minimize_loading'
  rolling_horizon: True
  load_results: False
  total_timesteps: 168
  timesteps_per_iteration: 24 # number of timesteps which are optimized in one
#  bulk
  overlap_iterations: 8 # overlapping timesteps at the end of each iteration
#  is added to the iteration for optimization but results are dropped
  iterations_per_era: 7 # an era defines a closed timeframe for optimization
#  in the last iteration of an era, the overlapping time steps are invented
logger:
  log_file: 'log.txt'
  log_to_file: True
grids:
  version: 0
  mvgds: [2534, 176, 177, 1056, 1690, 1811]
#  mvgds: [1056]
  load_integration:
    generator_scenario: "ego100"
    import: "elia_ding0_grids"
    export: "load_n_gen_grids"
  emob_integration:
    import: "load_n_gen_grids"
    export: "load_n_gen_n_emob_grids"
    to_freq: "1h"
    flexbands: ""
  hp_integration:
    import: "load_n_gen_n_emob_grids"
    export: "load_n_gen_n_emob_n_hp_grids"
  feeder_extraction:
    import: "load_n_gen_n_emob_n_hp_grids"
    export: "load_n_gen_n_emob_n_hp_grids_extracted"
    flexible_loads:
      hp: True
      bess: False
      emob: True
      emob_flex_sectors: ["work", "home"]
    only_flex_ev: False
  dnm_generation:
    feeder: False
    import: "load_n_gen_n_emob_n_hp_grids_extracted"
    export: "load_n_gen_n_emob_n_hp_grids_extracted"
telegram:
  token:
  chat_id:
