opt:
  version: 0
#  run_id: emob_hp_egon2035_nep_range_min_energy_level
#  run_id: emob_hp_egon2035_nep_range
  run_id: long_term
  log_to_stream: info
  log_to_files: info
  import_dir: load_n_gen_n_emob_n_hp_grids
  mvgds: [9999]
#  mvgds: [2534, 176, 177, 1056, 1690, 1811]
#  mvgds: [1056]
  fix_preparation: False
  solver: gurobi
  options:
    threads: 16
    OptimalityTol: 1e-5
    BarHomogeneous: 1
  save_lp_files: False
  save_solver_logs: False
  print_solver_logs: False
  flexible_loads:
    bess: False
    hp: True
    bev: True
    bev_flex_sectors: [ work, home ]
  start_datetime: 2011-01-01 00:00:00
#  total_timesteps: 168
  total_timesteps: 48
  rolling_horizon: False
  timesteps_per_iteration: 24 # number of timesteps which are optimized in one bulk
  overlap_iterations: 2
#  overlap_iterations: 6 # overlapping timesteps at the end of each iteration
#  is added to the iteration for optimization but results are dropped
#  iterations_per_era: 4
  iterations_per_era: 7 # an era defines a closed timeframe for optimization
#  in the last iteration of an era, the overlapping time steps are invented
