opt:
  mvgds: [2534, 176, 177, 1056, 1690, 1811]
#  mvgds: [2534]
  feeder: False
  solver: 'gurobi'
  opt_bess: False
  opt_hp: True
  opt_emob: True
  emob_sectors: ["work", "home"]
  objective: 'minimize_loading'
  rolling_horizon: True
  load_results: False
  timesteps_per_iteration: 24 # hours per day
  iterations_per_era: 7 # one week
  overlap_iterations: 6 # people start working at 6
logger:
  log_file: 'log.txt'
  log_to_file: True
grids:
  mvgds: [2534, 176, 177, 1056, 1690, 1811]
  load_integration:
    import: "elia_ding0_grids"
    export: "load_n_gen_grids"
  emob_integration:
    import: "load_n_gen_grids"
    export: "load_n_gen_n_emob_grids"
    to_freq: "1h"
    flexbands: ""
  hp_integration:
    import: "load_n_gen_n_emob_grids"
    export: "load_n_gen_n_emob_n_hp_grids"
  feeder_extraction:
    import: "load_n_gen_n_emob_n_hp_grids"
    export: "load_n_gen_n_emob_n_hp_grids_extracted"
    flexible_loads:
      hp: True
      bess: False
      emob: False
      emob_flex_sectors: ["work", "home"]
    only_flex_ev: False
  dnm_generation:
    import: "load_n_gen_n_emob_n_hp_grids_extracted"
    export: "load_n_gen_n_emob_n_hp_grids_extracted"
telegram:
  token:
  chat_id:
