model:
  grid-id: 176
  multi_grid_ids: [2534, 176, 177, 1056, 1690, 1811]
  feeder: False
  feeder-id: 0
opt:
  solver: 'gurobi'
  opt_storage: False
  opt_ev: False
  opt_hp: True
  objective: 'minimize_loading'
  timesteps_per_iteration: 96
  iterations_per_era: 7
  overlap_iterations: 24
logger:
  log_file: 'log.txt'
  log_to_file: True
grid_generation:
  grids: [2534, 176, 177, 1056, 1690, 1811]
  load_integration:
    import: "elia_ding0_grids"
    export: "load_n_gen_grids"
  emob_integration:
    import: "load_n_gen_grids"
    export: "load_n_gen_n_emob_grids"
    to_freq: "1h"
    flexbands: ""
  hp_integration:
    import: "load_n_gen_n_emob_grids"
    export: "load_n_gen_n_emob_n_hp_grids"
  feeder_extraction:
    import: "load_n_gen_n_emob_n_hp_grids"
    export: "load_n_gen_n_emob_n_hp_grids_extracted"
    flexible_loads: True
    only_flex_ev: False
  dnm_generation:
    import: "load_n_gen_n_emob_n_hp_grids_extracted"
    export: "downstream_node_matrix"