#egon-data:
#  --database-host: 127.0.0.1
#  --database-name: egon-data-sh-cts-je
#  --database-port: '59776'
#  --database-user: egon
#  --database-password: data
#  --dataset-boundary: Schleswig-Holstein
#  --random-seed: 42
egon-data:
  --database-host: 127.0.0.1
  --database-name: egon-data
  --database-port: '59776'
  --database-user: egon
  --database-password: data
  --dataset-boundary: Everything
  --random-seed: 42
